#!/usr/bin/env python3
"""
Architecture Generator
======================
Creates a real folder/file structure from tree-style architecture text.

Usage:
  python arch_generator.py                  # GUI mode (tkinter)
  python arch_generator.py --cli            # CLI mode (paste text in terminal)
  python arch_generator.py --file arch.txt  # File mode (read from .txt file)
  python arch_generator.py --help           # Show help
"""

import os
import sys
import re
import argparse


# ─── Parser ───────────────────────────────────────────────────────────────────

def get_indent_level(line: str) -> int:
    """Determine depth of a line based on tree characters."""
    depth = 0
    i = 0
    while i < len(line):
        c = line[i]
        if c in ('│', ' ', '\t'):
            depth += 1
        elif c in ('├', '└'):
            depth += 1
            break
        else:
            break
        i += 1
    return depth // 4


def parse_architecture(text: str) -> list[tuple[int, str, bool]]:
    """
    Parse architecture text into a list of (depth, name, is_dir) tuples.
    Handles both tree-format (├── └──) and plain indented format.
    """
    entries = []
    lines = text.splitlines()

    for raw in lines:
        if not raw.strip():
            continue

        # Remove tree drawing characters
        cleaned = re.sub(r'[│├└─]', ' ', raw)
        name = cleaned.strip()

        if not name:
            continue

        depth = get_indent_level(raw)
        is_dir = name.endswith('/') or ('.' not in name.split('/')[-1])

        entries.append((depth, name.rstrip('/'), is_dir))

    return entries


def build_paths(entries: list[tuple[int, str, bool]]) -> list[tuple[str, bool]]:
    """Convert (depth, name, is_dir) entries into full relative paths."""
    paths = []
    stack = []  # tracks current path components per depth

    for depth, name, is_dir in entries:
        stack = stack[:depth]
        stack.append(name)
        full_path = os.path.join(*stack)
        paths.append((full_path, is_dir))

    return paths


def create_structure(paths: list[tuple[str, bool]], base_dir: str = '.') -> tuple[int, int]:
    """Create directories and files. Returns (dirs_created, files_created)."""
    dirs_created = 0
    files_created = 0

    for rel_path, is_dir in paths:
        full = os.path.join(base_dir, rel_path)
        if is_dir:
            os.makedirs(full, exist_ok=True)
            dirs_created += 1
        else:
            os.makedirs(os.path.dirname(full), exist_ok=True)
            if not os.path.exists(full):
                open(full, 'w').close()
            files_created += 1

    return dirs_created, files_created


def generate_bash_script(paths: list[tuple[str, bool]]) -> str:
    """Generate a bash script that recreates the structure."""
    lines = ['#!/bin/bash', '# Auto-generated by arch_generator.py', '']
    for rel_path, is_dir in paths:
        if is_dir:
            lines.append(f'mkdir -p "{rel_path}"')
        else:
            lines.append(f'touch "{rel_path}"')
    return '\n'.join(lines)


# ─── CLI Mode ─────────────────────────────────────────────────────────────────

def cli_mode():
    print("=" * 50)
    print("  Architecture Generator — CLI Mode")
    print("=" * 50)
    print("Paste your architecture text below.")
    print("When done, enter a blank line followed by 'END' and press Enter.\n")

    lines = []
    while True:
        try:
            line = input()
            if line.strip().upper() == 'END':
                break
            lines.append(line)
        except EOFError:
            break

    text = '\n'.join(lines)
    if not text.strip():
        print("No input provided. Exiting.")
        return

    output_dir = input("\nOutput directory (press Enter for current directory): ").strip()
    if not output_dir:
        output_dir = '.'

    run_generation(text, output_dir)


# ─── File Mode ────────────────────────────────────────────────────────────────

def file_mode(filepath: str):
    if not os.path.exists(filepath):
        print(f"Error: File '{filepath}' not found.")
        sys.exit(1)

    with open(filepath, 'r', encoding='utf-8') as f:
        text = f.read()

    print(f"Read architecture from: {filepath}")
    output_dir = input("Output directory (press Enter for current directory): ").strip()
    if not output_dir:
        output_dir = '.'

    run_generation(text, output_dir)


# ─── Core Runner ──────────────────────────────────────────────────────────────

def run_generation(text: str, output_dir: str):
    entries = parse_architecture(text)
    if not entries:
        print("Could not parse any entries from the input.")
        return

    paths = build_paths(entries)

    print(f"\nParsed {len(paths)} entries ({sum(1 for _, d in paths if d)} dirs, {sum(1 for _, d in paths if not d)} files)")
    print(f"Output directory: {os.path.abspath(output_dir)}\n")

    confirm = input("Create structure? [y/N]: ").strip().lower()
    if confirm != 'y':
        print("Aborted.")
        return

    os.makedirs(output_dir, exist_ok=True)
    dirs, files = create_structure(paths, output_dir)
    print(f"\nDone! Created {dirs} directories and {files} files.")

    save_script = input("\nAlso save a bash script? [y/N]: ").strip().lower()
    if save_script == 'y':
        script = generate_bash_script(paths)
        script_path = os.path.join(output_dir, 'create_structure.sh')
        with open(script_path, 'w') as f:
            f.write(script)
        print(f"Bash script saved to: {script_path}")


# ─── GUI Mode ─────────────────────────────────────────────────────────────────

def gui_mode():
    try:
        import tkinter as tk
        from tkinter import ttk, filedialog, messagebox, scrolledtext
    except ImportError:
        print("tkinter is not available. Use --cli or --file mode instead.")
        sys.exit(1)

    root = tk.Tk()
    root.title("Architecture Generator")
    root.geometry("800x620")
    root.configure(bg='#f5f5f5')
    root.resizable(True, True)

    FONT_MONO = ('Courier New', 11)
    FONT_UI   = ('Segoe UI', 10) if sys.platform == 'win32' else ('Helvetica', 11)
    FONT_BOLD = ('Segoe UI', 10, 'bold') if sys.platform == 'win32' else ('Helvetica', 11, 'bold')
    BG        = '#f5f5f5'
    CARD      = '#ffffff'
    ACCENT    = '#2563eb'
    MUTED     = '#6b7280'

    # ── Header
    hdr = tk.Frame(root, bg=ACCENT, padx=20, pady=12)
    hdr.pack(fill='x')
    tk.Label(hdr, text="Architecture Generator", font=('Helvetica', 15, 'bold'),
             fg='white', bg=ACCENT).pack(side='left')

    # ── Main frame
    main = tk.Frame(root, bg=BG, padx=16, pady=12)
    main.pack(fill='both', expand=True)

    # ── Input section
    tk.Label(main, text="Paste architecture text:", font=FONT_BOLD, bg=BG, fg='#111').pack(anchor='w')
    text_area = scrolledtext.ScrolledText(main, font=FONT_MONO, height=14, wrap='none',
                                          relief='flat', bd=1, highlightthickness=1,
                                          highlightbackground='#d1d5db', highlightcolor=ACCENT)
    text_area.pack(fill='both', expand=True, pady=(4, 10))

    # ── Output dir row
    dir_row = tk.Frame(main, bg=BG)
    dir_row.pack(fill='x', pady=(0, 10))
    tk.Label(dir_row, text="Output directory:", font=FONT_UI, bg=BG, fg='#111').pack(side='left')
    dir_var = tk.StringVar(value=os.getcwd())
    dir_entry = tk.Entry(dir_row, textvariable=dir_var, font=FONT_UI, width=45,
                         relief='flat', bd=1, highlightthickness=1,
                         highlightbackground='#d1d5db', highlightcolor=ACCENT)
    dir_entry.pack(side='left', padx=(8, 6), ipady=4)

    def browse():
        d = filedialog.askdirectory()
        if d:
            dir_var.set(d)

    tk.Button(dir_row, text="Browse", font=FONT_UI, command=browse,
              relief='flat', bd=0, bg='#e5e7eb', activebackground='#d1d5db',
              padx=10, pady=4).pack(side='left')

    # ── Options row
    opt_row = tk.Frame(main, bg=BG)
    opt_row.pack(fill='x', pady=(0, 10))
    save_bash_var = tk.BooleanVar(value=True)
    tk.Checkbutton(opt_row, text="Also save bash script (create_structure.sh)",
                   variable=save_bash_var, bg=BG, font=FONT_UI, fg='#374151',
                   activebackground=BG).pack(side='left')

    # ── Status bar
    status_var = tk.StringVar(value="Ready.")
    status = tk.Label(main, textvariable=status_var, font=FONT_UI, bg=BG, fg=MUTED, anchor='w')
    status.pack(fill='x', pady=(0, 6))

    # ── Buttons
    btn_row = tk.Frame(main, bg=BG)
    btn_row.pack(fill='x')

    def do_generate():
        text = text_area.get('1.0', 'end').strip()
        if not text:
            messagebox.showwarning("No input", "Please paste architecture text first.")
            return
        out_dir = dir_var.get().strip() or '.'
        try:
            entries = parse_architecture(text)
            paths   = build_paths(entries)
            os.makedirs(out_dir, exist_ok=True)
            dirs, files = create_structure(paths, out_dir)

            if save_bash_var.get():
                script = generate_bash_script(paths)
                script_path = os.path.join(out_dir, 'create_structure.sh')
                with open(script_path, 'w') as f:
                    f.write(script)

            msg = f"Created {dirs} dirs & {files} files in:\n{os.path.abspath(out_dir)}"
            if save_bash_var.get():
                msg += "\n\nBash script saved as create_structure.sh"
            status_var.set(f"Done — {dirs} dirs, {files} files created.")
            messagebox.showinfo("Success", msg)
        except Exception as e:
            messagebox.showerror("Error", str(e))
            status_var.set(f"Error: {e}")

    def load_file():
        fp = filedialog.askopenfilename(filetypes=[('Text files', '*.txt'), ('All files', '*.*')])
        if fp:
            with open(fp, 'r', encoding='utf-8') as f:
                content = f.read()
            text_area.delete('1.0', 'end')
            text_area.insert('1.0', content)
            status_var.set(f"Loaded: {fp}")

    def clear_all():
        text_area.delete('1.0', 'end')
        status_var.set("Cleared.")

    tk.Button(btn_row, text="Generate Structure", font=FONT_BOLD, command=do_generate,
              bg=ACCENT, fg='white', relief='flat', bd=0,
              activebackground='#1d4ed8', activeforeground='white',
              padx=16, pady=7).pack(side='left', padx=(0, 8))

    tk.Button(btn_row, text="Load from file", font=FONT_UI, command=load_file,
              relief='flat', bd=0, bg='#e5e7eb', activebackground='#d1d5db',
              padx=12, pady=7).pack(side='left', padx=(0, 8))

    tk.Button(btn_row, text="Clear", font=FONT_UI, command=clear_all,
              relief='flat', bd=0, bg='#e5e7eb', activebackground='#d1d5db',
              padx=12, pady=7).pack(side='left')

    root.mainloop()


# ─── Entry Point ──────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='Generate file/folder structure from architecture text.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('--cli',  action='store_true', help='Run in CLI mode (paste text in terminal)')
    parser.add_argument('--file', metavar='PATH',      help='Read architecture from a .txt file')
    args = parser.parse_args()

    if args.file:
        file_mode(args.file)
    elif args.cli:
        cli_mode()
    else:
        gui_mode()


if __name__ == '__main__':
    main()